# Generated by Django 3.2.3 on 2021-06-01 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociationData_MODEL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ASS_NameAssociation', models.CharField(db_index=True, help_text='هذا الحقل مخصص لإسم الجمعية', max_length=100, verbose_name='إسم الجمعية')),
                ('ASS_Slug', models.SlugField(unique=True, verbose_name='الإسم التعريفي')),
                ('ASS_AssociationLogo', models.ImageField(db_index=True, default='Default_Image.png', upload_to='AssociationData_Image/', verbose_name='شعار الجمعية')),
                ('ASS_Address', models.CharField(db_index=True, max_length=250, verbose_name='العنوان')),
                ('ASS_Mobile', models.CharField(db_index=True, max_length=10, verbose_name='الجوال')),
                ('ASS_Phone', models.CharField(db_index=True, help_text='ضع مفتاح المدينة قبل الرقم مثال:012', max_length=250, verbose_name='الهاتف')),
                ('ASS_Email', models.EmailField(db_index=True, max_length=250, verbose_name='البريد الألكتروني')),
                ('ASS_BankAccount', models.CharField(db_index=True, help_text='مثال: SA000000', max_length=50, verbose_name='الحساب البنكي - الآيبان')),
            ],
            options={
                'ordering': ['ASS_NameAssociation'],
            },
        ),
        migrations.CreateModel(
            name='PersonalData_MODEL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PER_Avialable', models.BooleanField(db_index=True, default=True, verbose_name='حالة المشترك_نشط')),
                ('FER_Slug', models.SlugField(blank=True, unique=True, verbose_name='الإسم التعريفي')),
                ('PER_FirstName', models.CharField(db_index=True, max_length=50, verbose_name='الإسم الأول')),
                ('PER_FatherName', models.CharField(db_index=True, max_length=50, verbose_name='إسم الاب')),
                ('PER_GrandFatherName', models.CharField(db_index=True, max_length=50, verbose_name='إسم الجد')),
                ('PER_FamilyName', models.CharField(db_index=True, max_length=50, verbose_name='إسم العائلة')),
                ('PER_ImgePersonal', models.ImageField(db_index=True, default='Default_Image.png', upload_to='PersonalData_Image/', verbose_name='الصورة الشخصية')),
                ('PER_IdNumber', models.CharField(db_index=True, max_length=50, verbose_name='رقم الهوية الشخصية')),
                ('PER_Nationality', models.CharField(choices=[('SA', 'Saudi'), ('BA', 'Bahrain'), ('OM', 'Oman'), ('QA', 'Qatar'), ('KU', 'Kuwait'), ('EM', 'Emirates'), ('YE', 'Yemen')], db_index=True, default='SA', max_length=2, verbose_name='الجنسية')),
                ('PER_Mobile', models.CharField(db_index=True, max_length=10, verbose_name='الجوال')),
                ('PER_SocialStatusMarried', models.BooleanField(db_index=True, default=True, verbose_name='الحالة الإجتماعية - أعزب')),
                ('PER_SocialStatusUnmarried', models.BooleanField(db_index=True, verbose_name='الحالة الإجتماعية -متزوج')),
                ('PER_Date_joined', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنضمام للجمعية')),
                ('PER_Association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saving.associationdata_model', verbose_name='اسم الجمعية')),
                ('PER_Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='اسم المشترك')),
            ],
        ),
        migrations.CreateModel(
            name='HousingData_MODEL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HOU_Region', models.CharField(db_index=True, max_length=25, verbose_name='المنطقة')),
                ('HOU_City', models.CharField(db_index=True, max_length=25, verbose_name='المدينة')),
                ('HOU_District', models.CharField(db_index=True, max_length=25, verbose_name='الحي')),
                ('HOU_HomeAddress', models.CharField(db_index=True, max_length=100, verbose_name='عنوان المنزل')),
                ('HOU_CurrentWork', models.CharField(db_index=True, max_length=100, verbose_name='العمل الحالي')),
                ('HOU_WorkAddress', models.CharField(db_index=True, max_length=100, verbose_name='عنوان العمل')),
                ('HOU_Association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saving.associationdata_model', verbose_name='اسم الجمعية')),
                ('HOU_Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='اسم المشترك')),
            ],
            options={
                'ordering': ['HOU_Customer'],
            },
        ),
        migrations.CreateModel(
            name='FinancialData_MODEL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIN_ShareValue', models.DecimalField(db_index=True, decimal_places=2, max_digits=8, verbose_name='قيمة السهم')),
                ('FIN_NumberShares', models.IntegerField(db_index=True, default=1, verbose_name='عدد الأسهم')),
                ('FIN_BankName', models.CharField(db_index=True, max_length=50, verbose_name='إسم البنك')),
                ('FIN_BankAccount', models.CharField(db_index=True, max_length=50, verbose_name='الحساب البنكي - الآيبان')),
                ('FIN_MethodPaymentCash', models.BooleanField(db_index=True, default=True, verbose_name='طريقة سداد قيمة اﻷسهم _ نقدا')),
                ('FIN_MethodPaymentCheck', models.BooleanField(db_index=True, verbose_name='طريقة سداد قيمة اﻷسهم _ شيك')),
                ('FIN_MethodPaymentTransfer', models.BooleanField(db_index=True, verbose_name='طريقة سداد قيمة اﻷسهم _ حوالة')),
                ('FIN_MethodPayment', models.CharField(choices=[('CA', 'Cash'), ('CH', 'Check'), ('TR', 'Transfer')], db_index=True, default='CA', max_length=2, verbose_name='طريقة إستلام قيمة اﻷسهم')),
                ('FIN_SalaryDisbursementDate', models.DateField(db_index=True, verbose_name='تاريخ صرف الراتب')),
                ('FIN_DateShareReceived', models.DateField(db_index=True, verbose_name='تاريخ استلام اﻷسهم/المشاركات/المستحقات')),
                ('FIN_Association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saving.associationdata_model', verbose_name='اسم الجمعية')),
                ('FIN_Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='اسم المشترك')),
            ],
            options={
                'ordering': ['FIN_Customer'],
            },
        ),
    ]
