# Generated by Django 3.2.3 on 2021-06-29 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saving', '0007_alter_associationdata_model_ass_associationlogo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='associationdata_model',
            options={'ordering': ['ASS_NameAssociation', '-ASS_Mobile']},
        ),
    ]
