# Generated by Django 3.2.3 on 2021-07-08 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saving', '0010_auto_20210708_1600'),
        ('accounts', '0002_auto_20210708_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldata_model',
            name='PER_Association',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='saving.associationdata_model', verbose_name='اسم الجمعية'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personaldata_model',
            name='PER_SocialStatusEmployee',
            field=models.BooleanField(db_index=True, default=True, verbose_name='الحالة الإجتماعية -  طالب'),
        ),
    ]
