# Generated by Django 3.2.3 on 2021-07-09 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_personaldata_model_per_association'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaldata_model',
            old_name='FER_Slug',
            new_name='PER_Slug',
        ),
    ]
