# Generated by Django 3.2.3 on 2021-07-09 11:49

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_fer_slug_personaldata_model_per_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata_model',
            name='PER_Nationality',
            field=django_countries.fields.CountryField(db_index=True, max_length=2, verbose_name='الجنسية'),
        ),
    ]
